# SPDX-FileCopyrightText: 2021 HH Partners
#
# SPDX-License-Identifier: MIT

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      fossology:
        image: fossology/fossology
        ports:
          - 8080:80

    steps:
      - uses: actions/checkout@v2
      - name: Build and run tests
        run: cargo test --verbose -- --test-threads=1

  reuse:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v1
